### ISSUE TITLE
Clicking Platform Buttons Bug

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO/Docs#21]
When selecting iOS and then refreshing the page and then clicking iOS again, it doesn't update.

If I then click on Android and iOS again, it updates correctly.

https://user-images.githubusercontent.com/5754073/191785768-b5ac7a88-5fe9-48eb-83b6-176cc8da592b.mov

**Comment by Mr-spShuvo** [comment]
Resolved!
