### ISSUE TITLE
Agora Chat Images

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO/Docs#22]
Images for Agora Chat docs don't load for me. Tried multiple pages/platforms within chat.
@billy-the-fish also seeing this.

Images under other products work great.

<img width="1617" alt="Screenshot 2022-09-22 at 16 41 07" src="https://user-images.githubusercontent.com/5754073/191791921-06ebd3a9-0df5-433c-8ddd-e66820a62615.png">

**Comment by billy-the-fish** [comment]
Shuvo, this is the 403 problem we talked about before. You need to inject <meta name=“referrer” content=“no-referrer”> into the header and the images are visible.

**Comment by Mr-spShuvo** [comment]
Agora CDN needs to whitelist the domain. The script will not resolve this issue.
