### ISSUE TITLE
Missing platform in Interactive Whiteboard

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs#30]
Interactive Whiteboard supports Web, but it's missing in the platform config. @Mr-spShuvo Please add this before hard launch. Thanks!

<img width="761" alt="image" src="https://user-images.githubusercontent.com/73678648/192229988-e0ecd6bc-8c79-4431-b074-b5b659ce71fc.png">

**Comment by Mr-spShuvo** [comment]
Resolved!
