### ISSUE TITLE
Number of items to correct for Unity Video QuickStart

### ISSUE THREAD

**Issue by icywind** [AgoraIO/Docs#4]
Reviewing this doc:
https://agoradocs-internal.netlify.app/video-calling/get-started/get-started-sdk

Feedbacks:

1. **Prerequisites**, minimum Unity version is Unity 2017 LTS
2. [Implement a client for Video Calling](https://agoradocs-internal.netlify.app/video-calling/get-started/get-started-sdk/#implement-a-client-for-) - Grammar on _"their video and audio is rendered"_ , singular vs plural here.
3.  _“To create buttons that you access programmatically to implement the Video Calling workflow:”_   - a confusing sentence.  Just say “To create buttons using the Editor, click on menu Game Object > UI > Button”
4. Similarly in later section, _"To create raw images using Unity that you access programmatically to display video streams on"_. How about "To create raw images using the Editor"
5. Creating application level code in the SDK area. (Steps in _Create a new script to hold the system logic_). See further discussion in the comment.
6. In step 5 (Reference the UI elements from SampleScene),  `go = GameObject.Find(*Leave*);`.  Use quote (") instead of  * for strings.
7. In [Test your implementation](https://agoradocs-internal.netlify.app/video-calling/get-started/get-started-sdk/#test-your-implementation), _Agora recommends you run this project on a physical mobile device_ -> not necessary.  User can run the test from the Editor directly, or make a PC/Mac build, or mobile build.  For simplicity, just remove "mobile".   
8. Double text section of "API References"

**Comment by icywind** [comment]
Further comment on Issue#5:
User should not create application code in the SDK area (Assets/Agora-RTC-Plugin/Agora-Unity-RTC-SDK/Code).  Just create the JoinChannelVideo.cs in Assets folder.  Developer should know if a better working folder should be created. Suggesting edit:

Create a new script to hold the system logic

To create a new script, in your game:

In Projects, Right-click Asset, then click Create > C# Script.  The Editor will create a script named "NewBehaviourScript".

In Assets, rename NewBehaviourScript to JoinChannelVideo.

The template code is visible in Inspector.

**Comment by Mr-spShuvo** [comment]
This issue is related to the `Docs-Source` Repo.
Can you please post it there?

cc: @billy-the-fish
